### ISSUE TITLE
Which clients does the server support?

### ISSUE THREAD

**Issue by gmuth** [danielklecha/SharpIppNextServer#2]
Which clients does the printer support?
You only mention Netprinter: https://play.google.com/store/apps/details?id=hu.co.tramontana.netprinter

How about other clients provided by operating systems like Windows, Linux, macOS, iOS?

**Comment by danielklecha** [comment]
Hi,
I added IPP server to Windows using wizard and command (I mentioned about it in readme):
`add-printer -Name "SharpIpp on http://127.0.0.1:631" -DriverName "Microsoft IPP Class Driver" -PortName "http://127.0.0.1:631/"`
I used it with ipptool on linux with success.
I didn't add printer directly to linux/macOS/iOS but IPP protocol in version 1.1 should be compatible with all clients. There is a small chance that specific clients require some additional attribute not added to the IPP server but I didn't have any problems on Windows.

**Comment by andygarratt** [comment]
@danielklecha  I cannot get a printer to add using the wizard in Windows 11, it fails as per the screenshot in the other issue I raised. 

The server does seem to work well though using the add-printer powershell command.

**Comment by danielklecha** [comment]
@andygarratt I noticed the same thing yesterday. It was working when I tested it at least one year ago. I see that Windows 11 changed a protocol version from 1.0 to 2.0 in the IPP request. I need to find a time to analyze it.

**Comment by andygarratt** [comment]
Thanks @danielklecha, adding the printer using powershell add-printer still works fine.

Is there any easy way to change the printer capabilities being presented? For example adding additional media sizes, duplex properties etc?

Thanks for a great functional IPP server, there is a real shortage of them on here

**Comment by danielklecha** [comment]
@andygarratt You can add custom options to `Printer` section in `appsettings.json`. All available options are in `PrinterOptions.cs` file. Maybe I should change `string Media` to `string[] Media` to support a list of sizes...

I changed laptop and I have a problem with add-printer command but if it works on your side then it must be something with my machine...

**Comment by andygarratt** [comment]
@danielklecha add-printer in powershell worked find for me, let me test it on a clean virtual workstation to be 100% sure though.

Agreed on the media list :)

**Comment by danielklecha** [comment]
@andygarratt I extended the configuration in version 1.0.3.

I still can't add the IPP 1.1 printer to Windows 11.
There is an alternative command `Add-Printer -IppURL "http://localhost:631/"` but it also doesn't work for me.

**Comment by andygarratt** [comment]
@danielklecha  Here is a video of me adding it on a clean Windows 11 virtual machine

https://youtu.be/h2hBEhC-V2M

**Comment by danielklecha** [comment]
@andygarratt Nice, thanks.

I can't use `http://localhost:631/` as `PortName`. I get:
`Add-Printer: The specified port does not exist.  Use add-printerport to add a new port, or specify an existing port.`

I prepared a script which adds printer and I can send test page but... server never gets this page and system marks the test page as printed. I'm confused why this happened... Jobs folder is empty.
```
$driverName = "Microsoft IPP Class Driver"
$printerName = "SharpIppNext"
$hostname = "127.0.0.1"
$portName = "SharpIppNextPort"
$portNumber = 631

$driver = Get-PrinterDriver | Where-Object { $_.Name -eq $driverName }

if ($null -eq $driver) {
    Write-Host "Installing the printer driver: $driverName"
    Add-PrinterDriver -Name $driverName
} else {
    Write-Host "Driver $driverName is already installed."
}

$port = Get-PrinterPort | Where-Object { $_.Name -eq $portName }

if ($null -eq $port) {
    Write-Host "Creating IPP port: $portName with port $portNumber"
    Add-PrinterPort -Name $portName -PrinterHostAddress $hostname -PortNumber $portNumber
} else {
    Write-Host "Port $portName already exists."
}

$printer = Get-Printer | Where-Object { $_.Name -eq $printerName }

if ($null -eq $printer) {
    Write-Host "Adding printer: $printerName"
    Add-Printer -Name $printerName -DriverName $driverName -PortName $portName
    Write-Host "Printer $printerName added successfully."
} else {
    Write-Host "Printer $printerName already exists."
}
```

When I use `Add-Printer -IppURL "http://localhost:631/"` then I get an error:
`Add-Printer: The specified WSD or IPP print device was not found.  Ensure that the specified URL or UUID is correct, ensure the device is turned on, and ensure that network discovery is enabled.`

Maybe It's related to the build.
I use Windows 11 Enterprise 23H2 22631.4112.

I don't have a problem with IPP extension for Chrome.

**Comment by andygarratt** [comment]
@danielklecha Looking on my workstation from when I was testing with it running in Visual Studio i used http://127.0.0.1:631/ as the port

Not sure if its different to localhost, I know technically it isn't, but it might behave differently.

**Comment by andygarratt** [comment]
My workstation is also Windows 11 Enterprise 23H2, slightly updated though on 22631.4163

**Comment by chandralk** [comment]
Hi @danielklecha,

I'm running SharpIppNextServer on my local machine (Windows 10 Pro 22H2) and am trying to add a printer through the wizard.

I can see that the `Get-Printer-Attributes` request is being received by SharpIppNextServer and the response too is being sent successfully.

But Windows doesn't seem to be accepting the response as valid. The wizard fails with the following error:

> Windows couldn't connect to the printer.
> Check the printer name and try again. If this is a network printer, make sure the printer is turned on, and that the printer address is correct.

I checked the Windows Event Viewer and I can find 2 errors every time I attempt to add a printer:

> User Interaction Required while trying to get a token silently. ErrorCode: 0xcaa9004d, Error: Account type is unknown.
> mcpmanagementservice.dll

> Failed to get auth header with 0x8086000c
> mcpmanagementservice.dll

I am assuming that the response is missing some header and this is causing the issue. I went through IPP 1.1 as well as IPP 2.x RFCs to find out if there is any `auth header` which is missing from the response, but I'm not able to find anything.

Am I missing something here or is something wrong with my setup. Any light thrown on this would be greatly appreciated!

**Comment by danielklecha** [comment]
@chandralk I have similar issues on my machine (Windows 11). I've tried to install a printer using PowerShe, but the printer is ignored, or Windows makes a call for attributes and throws an error.
ipptool (linux) and chrome extension accepts this printer.
1. I need to think more about powershell script - maybe there is some workaround to handle that
2. Windows is sending request with IPP 2.0. Maybe it requires some additional attributes which were missing in IPP 1.1 server. I have plans to update the library and server to IPP 2.0 but I must modify request classes and update mappings because IPP 2.0 supports new groups with attributes (e.g. media). It's complicated to read the whole documentation.

**Comment by chandralk** [comment]
Hi @danielklecha,

If you could point me to the correct documentation, I can go through it, enhance the library and create a PR. I went through the [IPP Version 2.0, 2.1, and 2.2](https://ftp.pwg.org/pub/pwg/standards/std-ipp20-20151030-5100.12.pdf) standards document, but I couldn't find any references to additional Auth header(s) which are expected by the client.

**Comment by gmuth** [comment]
Why do you think Auth headers (http or ipp-attribute?) are required? Authentication should be an optional feature. So for general windows compatibility authentication should not be necessary from my point of view.
(I can't see why the event log entry from above is caused by an IPP server - tokens are not in use with ipp)

**Comment by danielklecha** [comment]
@chandralk I don't think that is a problem with authentication. The current implementation accepts all requests.
Windows should throw an error with information what is missing... It's a problem with the IPP version or some attribute is missing in <Get-Printer-Attributes>. But ipptool doesn't throw an error so I'm confused.

You pointed to the correct document but there are a few documents with extensions for IPP 1.1.
I like to use [the IPP registrations page](https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xhtml) because it contains links to documentation.

I want to rename NewJobAttributes to JobTemplateAttributes and extract non-related properties from this class.
Maybe I will find a time this month. I'm updating the IppSharpNext library, switching the reference in IppSharpNextServer to a local dll, and testing the server using ipptool from WSL. Unfortunately, ipptool has a limited range of tests, and it can't detect all missing things.

**Comment by danielklecha** [comment]
I fixed some bugs in `SharpIppNext` so I updated `SharpIppNextServer` app.
@gmuth @andygarratt I think I resolved all issues with automated installation in Windows. I added `Setup\Add-Printer.ps1` script to automate the process. I still didn't check how to add a printer manually.

Version 1.0.4 passes tests for IPP 2.0 (at least in ipptool): `ipptool -t ipp://172.25.192.1 ipp-2.0.test`

**Comment by danielklecha** [comment]
@gmuth I updated installation instructions in README. I think that should be enough.
Let me know if you have any concerns.

**Comment by PhilShipley** [comment]
@danielklecha I am still seeing issues when using the Windows add printer wizard

> I fixed some bugs in `SharpIppNext` so I updated `SharpIppNextServer` app. [@gmuth](https://github.com/gmuth) [@andygarratt](https://github.com/andygarratt) I think I resolved all issues with automated installation in Windows. I added `Setup\Add-Printer.ps1` script to automate the process. I still didn't check how to add a printer manually.
> 
> Version 1.0.4 passes tests for IPP 2.0 (at least in ipptool): `ipptool -t ipp://172.25.192.1 ipp-2.0.test`

Also, there seems to be 2.1 and 2.2 tests as well. Any plans for this?

**Comment by danielklecha** [comment]
@PhilShipley I did some tests...
1. open add document wizard
2. select "Add a printer using an IP address or hostname"
3. Select `IPP Device` as device type
4. Write `http://127.0.0.1:631/SharpIppNext` as `Hostname or IP address`
5. When I run it on debug then I can see 3 requests to the printer and printer returns it without issue.
6. Wizard displays popup "Windows couldn't connect to the printer (...)"

Maybe Windows requires to setup some other optional attributes.
I have a problem to figure it out.

Powershell script should work.

Regarding 2.1 and 2.2. Library support all methods from IPP 1.1. It passes tests for 2.0 but does not implement new operations from 2.0. There was also few extensions between 1.1 and 2.0 which are implemented partially. Maybe support for 2.1 and 2.2 will be added but not in near future.

**Comment by PhilShipley** [comment]
> [@PhilShipley](https://github.com/PhilShipley) I did some tests...
> 
> 1. open add document wizard
> 2. select "Add a printer using an IP address or hostname"
> 3. Select `IPP Device` as device type
> 4. Write `http://127.0.0.1:631/SharpIppNext` as `Hostname or IP address`
> 5. When I run it on debug then I can see 3 requests to the printer and printer returns it without issue.
> 6. Wizard displays popup "Windows couldn't connect to the printer (...)"
> 
> Maybe Windows requires to setup some other optional attributes. I have a problem to figure it out.
> 
> Powershell script should work.
> 
> Regarding 2.1 and 2.2. Library support all methods from IPP 1.1. It passes tests for 2.0 but does not implement new operations from 2.0. There was also few extensions between 1.1 and 2.0 which are implemented partially. Maybe support for 2.1 and 2.2 will be added but not in near future.

@danielklecha,

Regarding steps 1 through 6, I am seeing the exact same thing. There is a total of 21 'OperationAttributes' asked for in the 3 requests. They are the same for each request. They are:

uri-authentication-supported
document-format-default
document-format-preferred
document-format-supported
ipp-version-supported
media-supported
media-type-supported
mopria-certified
mopria_certified
printer-dns-sd-name
printer-firmware-name
printer-firmware-string-version
printer-device-id
printer-info
printer-location
printer-make-and-model
printer-more-info
printer-name
printer-uri-supported
printer-uuid
uri-security-supported

At the moment I am trying to add/research these to see if we can get past the error encountered at step 6.

**Comment by gmuth** [comment]
I wonder if it's save to say "there is an issue with IPP". Setting up a printer includes various steps using different protocols. The outcome of one step is than used as input for the next step. There is a difference in setting up a printer via CLI or via the GUI wizard. I don't know what Windows does internally but I guess choosing a driver is one of the things it is doing behind the wizard.

How can we make Windows choose the right driver?
What is the right driver anyway? IPP? Print to PDF?

How does setting up a real printer technically look like? 
Is WS-Discovery involved?
Which protocols are involved and what messages are returned by the printer?

Unfortunately the behavior and expectations of operating system towards printers are not very well documented.
And IPP does not cover everything related to printer handling (like discovery and setup).

**Comment by gmuth** [comment]
For linux the process is more obvious. PPDs have been the standard for a long time. With CUPS moving away from PPDs to driverless printing the overall direction for printer handling in general looks promising. However PPDs are still used internally as a proven interface to existing components. To close the gap to "driverless" after discovery CUPS queries the printers capabilities (Get-Printer-Attributes) and accordingly translates them into a (generic) PPD acknowledging the printers attributes (like color or monochrome). The file is then persisted as a printer config and used later when using the printer.

How does Windows implement the use case "keep printer config for later usage"?
Is there a command to list all the details of the printer config?
Is there an equivalent file or maybe registry entries that could be queried?

**Comment by PhilShipley** [comment]
@gmuth,

I was able to get things working using the wizard on my side. Not 100% sure exactly what 'piece' made everything happy, but part of the solution for me is/was to ensure that mDNS 'finds/discovers' the printer, rather than relying on having to add it manually.  This involved supplying 'proper' mDNS tags, proper service profile declarations and so on. As I specified earlier in my comments to @danielklecha, I added several of those initial 'missing' attributes as well. Now that I am actually getting/seeing more of what Windows wants, there are certainly more to add. I am still working through this, try to get a handle on everything, but wanted to at least report some progress. In my case, I want(ed) the IPP class driver to be selected (and it is), while also giving me a legitimate PSA ID to work with.  I do agree that real documentation is lacking for the Microsoft/Windows side of things, but truth be told, that is pretty much par for the course...after wrestling/dealing with Microsoft printing for nearly 30 years now.

**Comment by gmuth** [comment]
I experienced similar behavior with other operating systems (macOS, iOS, iPadOS). Technically the printer attributes could have the highest priority when acquiring information from different sources. However some data is kept from previous (discovery) steps and has an impact to the internal decision tree or control flow of the IPP driver implementation.
Unfortunately this behavior ist different for each client (os) and even seems to change with updates.
Documenting the client system version and setup steps would help a lot (assuming the server side stuff ends in git).

**Comment by danielklecha** [comment]
@PhilShipley I modified the code but wizard doesn't work.

1. Some of the attributes dosn't exist in IPP documentation like `document-format-preferred`
2. I noticed that if attribute is requested then server should return `novalue` but if property is null then server doesn't attach this property. It's correct because library doesn't know if it should be skipped or added with novalue. As a workaround I added method `ImproveGetPrinterAttributesRawResponse` in `SharpIppNextServer` that will use raw response, check requested attributes and add them with `novalue`.

Request is better but wizard return the same error.
Did you manually added values for this requested attributes? You could do it inside `ImproveGetPrinterAttributesRawResponse` - previously there was no way to access raw response.

How did you implemented mDNS? It's a different scenario because you don't need to paste URL but windows detects it.
I tested with `Makaretu.Dns.Multicast.New` and below implementation but without success.
```csharp
public class MdnsService : IHostedService
{
    private readonly ServiceDiscovery _serviceDiscovery = new();

    public Task StartAsync(CancellationToken cancellationToken)
    {
        var profile = new ServiceProfile("SharpIppNext", "_ipp._tcp", 631 );
        if (_serviceDiscovery.Probe(profile))
            throw new InvalidOperationException("Service name conflict detected on the network.");
        _serviceDiscovery.Advertise(profile);
        _serviceDiscovery.Announce(profile);
        Console.WriteLine("mDNS service advertising started.");
        return Task.CompletedTask;
    }

    public Task StopAsync(CancellationToken cancellationToken)
    {
        _serviceDiscovery.Unadvertise();
        _serviceDiscovery.Dispose();
        Console.WriteLine("mDNS service stopped.");
        return Task.CompletedTask;
    }
}
```

**Comment by danielklecha** [comment]
@gmuth @PhilShipley I'm able to add printer using printer wizard in Windows 11.
I compared `SharpIppNext` printer with `HP DeskJet 3700`. I found some differences in attributes and values. I updated code and created release `v1.0.6`.

1. open add document wizard
2. select "Add a printer using an IP address or hostname"
3. Select `IPP Device` as device type
4. Write `http://127.0.0.1:631/` or `https://127.0.0.1:631/` as `Hostname or IP address`
5. Click `Next` and printer should be added without issues.

Please, verify it on your side.

I still must update documentation.
It will be nice to have mDNS but require additional analyze.

**Comment by PhilShipley** [comment]
@gmuth, Below is how I implemented (for the time being). I am not 100% certain if all the txt records (properties) are actually 'working'. 

There are subtypes (noted below) that apparently are needed for Airprint to see the device from an IPhone/MacOS etc. 
I don't have that working yet. Maybe you can check what a linux disto sees on the wire....dns-sd or otherwsie.

```csharp
namespace SharpIppNextServer.Services;

public class MdnsAdvertiser : BackgroundService
{
    private readonly ILogger<MdnsAdvertiser> _logger;
    private MulticastService? mdns;
    private ServiceDiscovery? sd;

    public MdnsAdvertiser(ILogger<MdnsAdvertiser> logger)
    {
        _logger = logger;
    }

    protected override Task ExecuteAsync(CancellationToken stoppingToken)
    {
        _logger.LogInformation("Starting mDNS advertiser...");

        mdns = new MulticastService();
        sd = new ServiceDiscovery(mdns);

        var hostName = $"{Dns.GetHostName()}.local";

        const int ippPort = 631;                                                                                        // IPP Port is 631
        var baseIppService = new ServiceProfile("SharpIppNext ABC Series", "_ipp._tcp", ippPort)                        // This instance name (first param) is the 'friendly name' that shows up when 'adding a device' in Windows
        {
            HostName = hostName                                                                                         // This is the mDNS hostname that will be advertised 
        };
       // baseIppService.Subtypes = new List<string>() { "_universal._sub.", "_printer." };                             // Still trying to sort this out so Airprint will work based on mDNS 

        // Advertise AirPrint / Mopria TXT records
        baseIppService.AddProperty("txtvers", "1");                                                                     // TXT record version
        baseIppService.AddProperty("qtotal", "1");                                                                      // Number of queues
        baseIppService.AddProperty("rp", "ipp/print");                                                                  // Resource Path
        baseIppService.AddProperty("ty", "SharpIppNext ABC Series");                                                    // Printer model/name
        // service.AddProperty("adminurl", "http://my-printer.local");                                                  // Admin Url (Optional)
        baseIppService.AddProperty("note", "Internet");                                                                 // Location
        baseIppService.AddProperty("product", "MFG:SharpIppNext;MDL:ABC;CMD:PDF,POSTSCRIPT,HPGL,TIF;");    	            // IEEE 1284 product string 
        baseIppService.AddProperty("UUID", "670e8400-e29b-41d4-a716-446655440000");                                     // Must match IPP UUID
        baseIppService.AddProperty("priority", "0");                                                                    // Queue priority
        baseIppService.AddProperty("pdl", "application/pdf");                                                           // Supported formats for IPP
        baseIppService.AddProperty("Color", "T");                                                                       // Color support (T/F)
        baseIppService.AddProperty("Duplex", "F");                                                                      // Duplex support (T/F)
     	//baseIPPservice.AddProperty("usb_MFG", "SharpIppNext");                                                        // USB vendor (Not needed as we are not USB connected?) 
     	//baseIPPservice.AddProperty("usb_MDL", "ABC");                                                                 // USB model (Not needed as we are not USB connected?) 
        baseIppService.AddProperty("air", "print");                                                                     // AirPrint compatibility flag    

        sd.Advertise(baseIppService);

        mdns.Start();

        // Stop mDNS cleanly when cancellation is triggered
        stoppingToken.Register(() =>
        {
            _logger.LogInformation("Stopping mDNS advertiser...");
            mdns.Stop();
        });

        return Task.CompletedTask;
    }

    public override void Dispose()
    {
        mdns?.Dispose();
        base.Dispose();
    }
}
```

**Comment by PhilShipley** [comment]
> [@gmuth](https://github.com/gmuth) [@PhilShipley](https://github.com/PhilShipley) I'm able to add printer using printer wizard in Windows 11. I compared `SharpIppNext` printer with `HP DeskJet 3700`. I found some differences in attributes and values. I updated code and created release `v1.0.6`.
> 
> 1. open add document wizard
> 2. select "Add a printer using an IP address or hostname"
> 3. Select `IPP Device` as device type
> 4. Write `http://127.0.0.1:631/` or `https://127.0.0.1:631/` as `Hostname or IP address`
> 5. Click `Next` and printer should be added without issues.
> 
> Please, verify it on your side.
> 
> I still must update documentation. It will be nice to have mDNS but require additional analyze.

At a quick glance, your latest commit looks very similar to what I have done as far as attributes. I went a step further and added them in SharpIppNext so they could be used strongly typed and so on. You had made mention earlier of attributes like: document-format-supported and document-format-default....whereas these don't seem to be officially documented, they may seem to indicate how/what the Microsoft IPP Class Driver (at least) will produce....when used.

**Comment by danielklecha** [comment]
@PhilShipley I was extending library using IPP documentation. I like to use [www.iana.org](https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xhtml) because it contains complete list.

I cannot find `document-format-preferred`, `mopria-certified`, `mopria_certified`. They must be undocumented.

This attributes are from PWG5100.13 and PWG5107.2:
- `printer-dns-sd-name`
- `printer-firmware-name`
- `printer-firmware-string-version`
- `printer-uuid`
- `printer-device-id`

`SharpIppNext` contains almost all attributes from IPP 1.1 but extensions are added partially.

**Comment by PhilShipley** [comment]
@danielklecha Yes, there are a lot of extensions (and operations) that would be useful to support (as they directly relate to IPP Everywhere).
